import { afterEach, describe, expect, test, vi } from "vitest";
import { generateImage } from "ai";
import { internal } from "./_generated/api";
import { makeTest, seedFixture } from "./runtime/fixtures.test";

vi.mock("ai", async (importOriginal) => ({
  ...(await importOriginal<typeof import("ai")>()),
  generateImage: vi.fn(),
}));
afterEach(() => {
  vi.unstubAllEnvs();
  vi.clearAllMocks();
});

async function setup() {
  const t = makeTest();
  const fx = await seedFixture(t);
  vi.stubEnv("AI_GATEWAY_API_KEY", "test-only");
  vi.stubEnv("AVATAR_IMAGE_MODEL", "test/image");
  await t.run((ctx) =>
    ctx.db.patch("teams", fx.teamAId, {
      avatarTemplate: "bolt",
      avatarStatus: "generating",
      avatarRequestKey: "image-job",
    }),
  );
  return {
    t,
    fx,
    args: {
      teamId: fx.teamAId,
      runId: fx.runId,
      stepIndex: 0,
      requestKey: "image-job",
      name: "Team A",
      prompt: "A lightning crest",
    },
  };
}

describe("avatar generation", () => {
  test("stores generated bytes, serves the avatar, bills once and skips duplicate jobs", async () => {
    const { t, fx, args } = await setup();
    vi.mocked(generateImage).mockResolvedValue({
      image: {
        mediaType: "image/png",
        uint8Array: new Uint8Array([137, 80, 78, 71]),
      },
      calls: [{ providerMetadata: { gateway: { cost: "0.04" } } }],
      usage: { inputTokens: 12, outputTokens: 8 },
    } as never);
    await t.action(internal.avatar_generation.generate, args);
    await t.action(internal.avatar_generation.generate, args);
    expect(generateImage).toHaveBeenCalledTimes(1);
    const team = await t.run((ctx) => ctx.db.get("teams", fx.teamAId));
    expect(team?.avatarStatus).toBe("ready");
    expect(team?.avatarStorageId).toBeTruthy();
    await t.mutation(internal.team_identity.finish, {
      teamId: fx.teamAId,
      requestKey: args.requestKey,
      storageId: team!.avatarStorageId!,
    });
    expect(
      await t.run((ctx) => ctx.storage.getUrl(team!.avatarStorageId!)),
    ).toBeTruthy();
    const events = await t.run((ctx) =>
      ctx.db
        .query("usage_events")
        .withIndex("by_runId_stepIndex", (q) => q.eq("runId", fx.runId))
        .take(10),
    );
    expect(events).toHaveLength(1);
    expect(events[0].costUsd).toBe(0.04);
    expect(events[0].stepIndex).toBe(-1);
    // The recovery timer must not overwrite a completed image.
    await t.mutation(internal.team_identity.finish, {
      teamId: fx.teamAId,
      requestKey: args.requestKey,
      error: "Timeout",
    });
    expect(
      (await t.run((ctx) => ctx.db.get("teams", fx.teamAId)))?.avatarStatus,
    ).toBe("ready");
  });
  test("provider failures preserve the template and surface a safe error", async () => {
    const { t, fx, args } = await setup();
    vi.mocked(generateImage).mockRejectedValue(
      new Error("sensitive provider error"),
    );
    await t.action(internal.avatar_generation.generate, args);
    const team = await t.run((ctx) => ctx.db.get("teams", fx.teamAId));
    expect(team).toMatchObject({
      avatarStatus: "failed",
      avatarTemplate: "bolt",
    });
    expect(team?.avatarError).not.toContain("sensitive");
  });
});
